Repository kube-arbiter/website, pull requests merged in 2022-10, with the labels that each got.

#1 feat: add doc for 'tasks/create-observer-plugin'
  docs/Tasks/create-observer-plugin.md
Labels: size/L

#2 update observer and plugin doc
  docs/Concepts/observer-plugin.md
  docs/Concepts/observer.md
Labels: size/L

#3 feat: add e2e-test doc
  docs/Contribute/e2e-test.md
Labels: size/M

#4 update executor concepts
  docs/Concepts/executor.md
Labels: size/L

#6 feat: add observer zh-cn doc
  docs/Concepts/observer.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Concepts/observer.md
Labels: size/L

#7 feat: add obi concepts doc
  docs/Concepts/obi.md
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Concepts/obi.md
Labels: size/M

#8 feat: add observer-plugin zh-cn doc
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Concepts/observer-plugin.md
Labels: size/L

#9 feat: add executor zh-cn doc
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Concepts/executor.md
Labels: size/L

#10 fix: remove duplicate code
  i18n/zh-Hans/code.json
Labels: size/XS

#11 feat: init github action
  .github/auto_request_review.yml
  .github/dependabot.yml
  .github/workflows/auto_assign_reviewers.yml
  .github/workflows/greetings.yml
  .github/workflows/markdownlint.yml
Labels: size/M

#13 feat: add e2e-test zh-cn doc
  i18n/zh-Hans/docusaurus-plugin-content-docs/current/Contribute/e2e-test.md
Labels: size/L

#14 fix: update wrong script name
  docs/Contribute/e2e-test.md
Labels: size/XS
